version: "3.3"
services:
  gnpy:
    build:
      context: ./
      dockerfile: Dockerfile-compose
    volumes:
       - ./:/oopt-gnpy/shared_folder
#       - ./examples:/examples
         #         cp ./*.* ../
    #command: ["cp ./*.* ../"]
    entrypoint: ./run.sh
